played_with_me/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import web_app


urlpatterns = [
    # Examples:
    # url(r'^$', 'played_with_me.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('web_app.urls', namespace='web_app')),
    url(r'^admin/', include(admin.site.urls)),
]

web_app/urls.py
from django.conf.urls import patterns, url

from web_app import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url('^matches/(?P<match_id>\d+)/$', views.match_detail, name='match_details'),
    url('^players/(?P<player_id>\d+)/$', views.player_detail, name='player_details'),
    url('^friends/(?P<players>(\d+/){2,})$', views.friends_detail, name='friends_detail'),
    url('^players/(?P<player_id>\d+)/download/$', views.download_games, name='player_download'),

)

web_app/models.py
from django.db import models
from dota2api.api import *
import logging
import tasks
# Create your models here.
from django.db import transaction

dota_api = Initialise()

def get_total_matches_in_server(account):
    result = get_until_success(lambda: dota_api.get_match_history(account.steam_id))
    return result.total_results

def get_until_success(get_function):
    while True:
        try:
            import time
            time.sleep(1)
            return get_function()
        except Exception as e:
            import logging

            logging.exception(e)


def get_account(account_id):
    steam_id = convert_to_64_bit(account_id)
    summaries = get_until_success(lambda: dota_api.get_player_summaries(steam_id))

    if summaries:
        account, account_created = Account.objects.get_or_create(account_id=account_id)
        account_response = summaries[0]

        account.community_visibility_state = account_response.community_visibility_state
        account.profile_state = account_response.profile_state
        account.persona_name = account_response.persona_name
        account.last_logoff = account_response.last_logoff
        account.profile_url = account_response.profile_url
        account.url_avatar = account_response.url_avatar
        account.url_avatar_medium = account_response.url_avatar_medium
        account.url_avatar_full = account_response.url_avatar_full
        account.persona_state = account_response.persona_state
        account.primary_clan_id = account_response.primary_clan_id
        account.time_created = account_response.time_created
        account.persona_state_flags = account_response.persona_state_flags
        account.save()
        return account

    return None


def get_details_match(match_id):
    match = DetailMatch.objects.filter(match_id=match_id)
    if match:
        return match[0]
    else:
        details = get_until_success(lambda: dota_api.get_match_details(match_id))
        return parse_from_details_match(details)


def load_team(match, players):
    for player_response in players:
        hero, hero_created = Hero.objects.get_or_create(hero_id=player_response.hero.id,
                                                        localized_name=player_response.hero.localized_name,
                                                        name=player_response.hero.name,
                                                        url_small_portrait=player_response.hero.url_small_portrait,
                                                        url_large_portrait=player_response.hero.url_large_portrait,
                                                        url_full_portrait=player_response.hero.url_full_portrait,
                                                        url_vertical_portrait=player_response.hero.url_vertical_portrait)

        account = get_account(player_response.account_id)

        player = DetailMatchPlayer.objects.create(match=match, player_account=account,
                                                  account_id=player_response.account_id,
                                                  player_slot=player_response.player_slot,
                                                  hero=hero, kills=player_response.kills,
                                                  deaths=player_response.deaths, assists=player_response.assists,
                                                  leaver_status=player_response.leaver_status,
                                                  gold=player_response.gold,
                                                  last_hits=player_response.last_hits, denies=player_response.denies,
                                                  gold_per_min=player_response.gold_per_min,
                                                  xp_per_min=player_response.xp_per_min,
                                                  gold_spent=player_response.gold_spent,
                                                  hero_damage=player_response.hero_damage,
                                                  tower_damage=player_response.tower_damage,
                                                  hero_healing=player_response.hero_healing,
                                                  level=player_response.level)

        for additional_unit in player_response.additional_units:
            unit, unit_created = AdditionalUnit.objects.get_or_create(unit_name=additional_unit.unit_name,
                                                                      player=player)
            for index, item_response in enumerate(additional_unit.items):
                item, item_created = Item.objects.get_or_create(item_id=item_response.id,
                                                                localized_name=item_response.localized_name,
                                                                name=item_response.name,
                                                                is_recipe=bool(item_response.is_recipe),
                                                                in_secret_shop=item_response.in_secret_shop,
                                                                cost=item_response.cost,
                                                                in_side_shop=item_response.in_side_shop,
                                                                url_image=item_response.url_image)

                DetailMatchOwnerItem.objects.create(owner=unit, slot=index, item=item)

        for index, item_response in enumerate(player_response.items):
            item, item_created = Item.objects.get_or_create(item_id=item_response.id,
                                                            localized_name=item_response.localized_name,
                                                            name=item_response.name,
                                                            is_recipe=bool(item_response.is_recipe),
                                                            in_secret_shop=item_response.in_secret_shop,
                                                            cost=item_response.cost,
                                                            in_side_shop=item_response.in_side_shop,
                                                            url_image=item_response.url_image)

            DetailMatchOwnerItem.objects.create(owner=player, slot=index, item=item)

        for upgrade in player_response.ability_upgrades:
            ability, ability_created = Ability.objects.get_or_create(ability_id=upgrade.ability,
                                                                     name=upgrade.ability_name)
            DetailMatchAbilityUpgrade.objects.create(player=player,
                                                     ability=ability,
                                                     time=upgrade.time,
                                                     upgraded_lvl=upgrade.level)


def parse_from_details_match(match_details):
    match = DetailMatch.objects.create(is_radiant_win=match_details.is_radiant_win, duration=match_details.duration,
                                       start_time=match_details.start_time, match_id=match_details.match_id,
                                       match_seq_num=match_details.match_seq_num,
                                       tower_status_radiant=match_details.tower_status_radiant,
                                       tower_status_dire=match_details.tower_status_dire,
                                       barracks_status_radiant=match_details.barracks_status_radiant,
                                       barracks_status_dire=match_details.barracks_status_dire,
                                       cluster=match_details.cluster,
                                       cluster_name=match_details.cluster_name,
                                       first_blood_time=match_details.first_blood_time,
                                       lobby_type=match_details.lobby_type, lobby_name=match_details.lobby_name,
                                       human_players=match_details.human_players, league_id=match_details.league_id,
                                       positive_votes=match_details.positive_votes,
                                       negative_votes=match_details.negative_votes,
                                       game_mode=match_details.game_mode, game_mode_name=match_details.game_mode_name)

    load_team(match, match_details.players)

    return match


class Account(models.Model):
    account_id = models.BigIntegerField(unique=True)
    steam_id = models.BigIntegerField(null=True)
    community_visibility_state = models.IntegerField(null=True)
    profile_state = models.IntegerField(null=True)
    persona_name = models.CharField(max_length=500, null=True)
    last_logoff = models.BigIntegerField(null=True)
    profile_url = models.CharField(max_length=500, null=True)
    url_avatar = models.CharField(max_length=500, null=True)
    url_avatar_medium = models.CharField(max_length=500, null=True)
    url_avatar_full = models.CharField(max_length=500, null=True)
    persona_state = models.IntegerField(null=True)
    primary_clan_id = models.BigIntegerField(null=True)
    time_created = models.BigIntegerField(null=True)
    persona_state_flags = models.BigIntegerField(null=True)


class Hero(models.Model):
    hero_id = models.SmallIntegerField()
    localized_name = models.CharField(max_length=50)
    name = models.CharField(max_length=50, unique=True)
    url_small_portrait = models.CharField(max_length=300)
    url_large_portrait = models.CharField(max_length=300)
    url_full_portrait = models.CharField(max_length=300)
    url_vertical_portrait = models.CharField(max_length=300)


class Item(models.Model):
    item_id = models.SmallIntegerField(unique=True)
    localized_name = models.CharField(max_length=40)
    name = models.CharField(max_length=40)
    is_recipe = models.BooleanField()

web_app/views.py
# -*- coding: utf-8 -*-
from django.db import transaction
from django.shortcuts import render
from django.contrib import messages
import models
import dota2api
import logging
import os
import tasks
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


logger = logging.getLogger(__name__)

is_dev = os.environ.get('ENVIRONMENT', None)

# Create your views here.
def index(request):
    return render(request, 'web_app/index.html')


@transaction.atomic
def match_detail(request, match_id):
    match = models.get_details_match(match_id)
    return render(request, 'web_app/match_detail.html', {
        'match': match
    })


def player_detail(request, player_id):
    acc = models.get_account(int(player_id))
    models.DetailMatchPlayer.objects.aggregate()
    raw = models.Account.objects.raw(
        'SELECT dmp2.player_account_id as id,  count(*) as qtd    FROM web_app_account acc   JOIN web_app_detailmatchplayer dmp1 ON acc.id = dmp1.player_account_id   JOIN web_app_detailmatchplayer dmp2 ON dmp1.match_id = dmp2.match_id WHERE dmp1.player_account_id = ' + str(
            acc.id) + ' and dmp2.player_account_id <> ' + str(
            acc.id) + ' GROUP BY dmp1.player_account_id,dmp2.player_account_id HAVING count(*) > 1 ORDER BY count(*)   DESC'
    )
    return render(request, 'web_app/account.html', {
        'account': acc,
        'friends': raw

    })


def friends_detail(request, players):
    accounts_ids = players.split("/")[:-1]
    radiant_matches = models.DetailMatch.objects.distinct().order_by('-start_time')
    for account_id in accounts_ids:
        radiant_matches = radiant_matches.filter(players__player_account__account_id=account_id)

    matches_query = radiant_matches

    total_matches = len(matches_query)

    paginator = Paginator(matches_query, 25)
    page = request.GET.get('page')
    try:
        matches = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        matches = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        matches = paginator.page(paginator.num_pages)

    return render(request, 'web_app/friend_matches.html', {
        'accounts': models.Account.objects.filter(account_id__in=accounts_ids),
        'total_matches': total_matches,
        'matches': matches
    })


def download_games(request, player_id):
    try:
        if not is_dev:
            tasks.download_games(player_id)
        account = models.Account.objects.get(account_id=player_id)
        total_matches = models.get_total_matches_in_server(account)
        already_downloaded_games = len(account.match_players.all())
        matches_to_download = total_matches - already_downloaded_games

        if matches_to_download > 0:
            return JsonResponse({
                'type': 'success',
                'message': 'Started to download {} matches'.format(matches_to_download)
            })
        else:
            return JsonResponse({
                'type': 'success',
                'message': 'All matches synchronized'
            })
    except Exception as e:
        return JsonResponse({
            'type': 'error',
            'message': 'Erro: ' + e.message
        })

web_app/templates/web_app/account.html
{% extends "base.html" %}


{% block content %}
    <div class="row">
        <div class="col-md-1">
            {{ account.persona_name }}
        </div>
        <div class="col-md-3">
            <img src="{{ account.url_avatar_full }}">
        </div>
        <div class="col-md-1">
        <button class="button" onclick="download_games('{% url 'web_app:player_download' account.account_id %}')">Synchronize Games</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <table>
                <tbody>
                {% for friend in friends %}
                    <tr>
                        <td>
                            <a href="{% url 'web_app:player_details' friend.account_id %}">{{ friend.persona_name }}</a>
                        </td>
                        <td>
                            {% with account.account_id|stringformat:"s"|add:"/" as account_url %}
                                {% with friend.account_id|stringformat:"s"|add:"/" as friend_url %}
                                    {% with account_url|add:friend_url as blah %}
                                        <a href="{% url 'web_app:friends_detail' blah %}">{{ friend.qtd }}</a>
                                    {% endwith %}
                                {% endwith %}
                            {% endwith %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

web_app/templates/web_app/friend_matches.html
{% extends "base.html" %}


{% block content %}

    <table class="table table-striped">
    {% for a in accounts %}
            <tr>
                <td>
                    {% include 'web_app/includes/syntatic_account.html' with account=a %}
                </td>
            </tr>
        {% endfor %}
    </table>
    You guys have {{ total_matches }} matches together.
    <table class="table table-striped">
        {% for m in matches %}
            <tr>
                <td>
                    {% include "web_app/includes/syntatic_game.html" with match=m accounts=accounts %}
                </td>
            </tr>
        {% endfor %}
    </table>

<div class="pagination">
    <span class="step-links">
        {% if matches.has_previous %}
            <a href="?page={{ matches.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ matches.number }} of {{ matches.paginator.num_pages }}.
        </span>

        {% if matches.has_next %}
            <a href="?page={{ matches.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

web_app/templates/web_app/index.html
{% extends "base.html" %}


{% block content %}
eita

{% endblock %}

web_app/templates/web_app/match_detail.html
{% extends "base.html" %}


{% block content %}
    <a href="{% url 'web_app:match_details' match.match_id %}">{{ match.match_id }}</a>
    {% if match.is_radiant_win %}
        <div>Radiant win!</div>
    {% else %}
        <div>Dire win!</div>
    {% endif %}
    <div>Duration: {{ match.duration }}</div>
    <div>Region: {{ match.cluster_name }}</div>
    <div>Mode: {{ match.game_mode_name }}</div>
    <div>Tower status radiant: {{ match.tower_status_radiant }}</div>
    <div>Tower status dire: {{ match.tower_status_dire }}</div>
    <table class="table">
        <thead>
        <tr>
            <th class="col-lg-1">id</th>
            <th class="col-lg-1">slot</th>
            <th class="col-lg-1">hero</th>
            <th class="col-lg-1">kills</th>
            <th class="col-lg-1">deaths</th>
            <th class="col-lg-1">assists</th>
            <th class="col-lg-1">gold</th>
            <th class="col-lg-1">last_hits</th>
            <th class="col-lg-1">denies</th>
            <th class="col-lg-1">gold_per_min</th>
            <th class="col-lg-1">xp_per_min</th>
            <th class="col-lg-1">gold_spent</th>
            <th class="col-lg-1">hero_damage</th>
            <th class="col-lg-1">hero_healing</th>
            <th class="col-lg-1">level</th>
            <th class="col-lg-1">items</th>


        </tr>
        </thead>

        <tbody>
        {% for player in match.radiant_team %}
            <tr>
                {% if player.player_account %}
                    <th class="col-lg-1">
                        <a href="{% url 'web_app:player_details' player.player_account.account_id %}">{{ player.player_account.persona_name }}</a>
                    </th>
                {% else %}
                    <th class="col-lg-1">{{ 'private profile' }}</th>
                {% endif %}
                <th class="col-lg-1">{{ player.player_slot }}</th>

                <th class="col-lg-1"><img width="105" height="55" src="{{ player.hero.url_large_portrait }}"></th>
                <th class="col-lg-1">{{ player.kills }}</th>
                <th class="col-lg-1">{{ player.deaths }}</th>
                <th class="col-lg-1">{{ player.assists }}</th>
                <th class="col-lg-1">{{ player.gold }}</th>
                <th class="col-lg-1">{{ player.last_hits }}</th>
                <th class="col-lg-1">{{ player.denies }}</th>
                <th class="col-lg-1">{{ player.gold_per_min }}</th>
                <th class="col-lg-1">{{ player.xp_per_min }}</th>
                <th class="col-lg-1">{{ player.gold_spent }}</th>
                <th class="col-lg-1">{{ player.hero_damage }}</th>
                <th class="col-lg-1">{{ player.hero_healing }}</th>
                <th class="col-lg-1">{{ player.level }}</th>
                <th class="col-lg-1">
                    {% for item in player.items.all %}
                        <img height="30" width="40" src="{{ item.item.url_image }}">
                    {% endfor %}
                    {% for unit in player.additional_units.all %}
                        {% for item in unit.items.all %}
                            <img height="30" width="40" src="{{ item.item.url_image }}">
                        {% endfor %}
                    {% endfor %}
                </th>

            </tr>

        {% endfor %}
        {% for player in match.dire_team %}
            <tr>
                {% if player.player_account %}
                    <th class="col-lg-1">
                        <a href="{% url 'web_app:player_details' player.player_account.account_id %}">{{ player.player_account.persona_name }}</a>
                    </th>
                {% else %}
                    <th class="col-lg-1">{{ 'private profile' }}</th>
                {% endif %}
                <th class="col-lg-1">{{ player.player_slot }}</th>

                <th class="col-lg-1"><img width="105" height="55" src="{{ player.hero.url_large_portrait }}"></th>
                <th class="col-lg-1">{{ player.kills }}</th>
                <th class="col-lg-1">{{ player.deaths }}</th>
                <th class="col-lg-1">{{ player.assists }}</th>
                <th class="col-lg-1">{{ player.gold }}</th>
                <th class="col-lg-1">{{ player.last_hits }}</th>
                <th class="col-lg-1">{{ player.denies }}</th>
                <th class="col-lg-1">{{ player.gold_per_min }}</th>
                <th class="col-lg-1">{{ player.xp_per_min }}</th>
                <th class="col-lg-1">{{ player.gold_spent }}</th>
                <th class="col-lg-1">{{ player.hero_damage }}</th>
                <th class="col-lg-1">{{ player.hero_healing }}</th>
                <th class="col-lg-1">{{ player.level }}</th>
                <th class="col-lg-1">
                    {% for item in player.items.all %}
                        <img height="30" width="40" src="{{ item.item.url_image }}">
                    {% endfor %}
                    {% for unit in player.additional_units.all %}
                        {% for item in unit.items.all %}
                            <img height="30" width="40" src="{{ item.item.url_image }}">
                        {% endfor %}
                    {% endfor %}
                </th>

            </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock %}